<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registo</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB"
      crossorigin="anonymous"
    />
    <style>
      html,
      body {
        height: 100%;
      }
      body {
        display: flex;
        align-items: center;
        justify-content: center;
        background: #f1f3f5;
        margin: 0;
      }
      .login-card {
        width: 100%;
        max-width: 500px;
        border-radius: 12px;
        box-shadow: 0 6px 24px rgba(18, 38, 63, 0.08);
      }
    </style>
  </head>
  <body>
    <main class="card login-card pt-1 pb-4 px-4 bg-white">
      <div class="card-body">
        <form action="/criar_conta" method="post">
          <h4 class="card-title mb-3 text-center">Registo</h4>
          <div class="form-floating mb-3">
            <input
              type="email"
              class="form-control"
              id="floatingInput"
              placeholder="name@example.com"
              name="email"
              required
            />
            <label for="floatingInput">Email address</label>
          </div>
          <div class="form-floating mb-3">
            <input
              type="password"
              class="form-control"
              id="floatingPassword"
              placeholder="Password"
              name="password"
              required
            />
            <label for="Password">Palavra-passe</label>
          </div>
          <div class="form-floating mb-3">
            <input
              type="password"
              class="form-control"
              id="floatingPassword"
              placeholder="Confirm Password"
              name="password2"
              required
            />
            <label for="Confirm Password"> Confirmar Palavra-passe</label>
          </div>
          <?php if (!empty($this->view->erro)): ?>
          <h6 style="color: red"><?= $this->view->erro ?></h6>
          <?php endif; ?>
          <button type="submit" class="btn btn-primary w-100">Registar</button>
          <p class="text-center mt-3 small">Se já estiver registado, <a href="/login">Login</a></p>
        </form>
      </div>
    </main>

  </body>
</html>
